
version: 2
jobs:
  build:
    docker:
      - image: openjdk:8
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: install coursier
          command: curl -L -o coursier https://git.io/vgvpD && chmod +x coursier

      - run:
          name: install scalafmt
          command: ./coursier bootstrap org.scalameta:scalafmt-cli_2.12:2.0.0-RC4 -r bintray:scalameta/maven -o scalafmt --main org.scalafmt.cli.Cli

      - run:
          name: install mill
          command: sh -c '(echo "#!/usr/bin/env sh" && curl -L https://github.com/lihaoyi/mill/releases/download/0.4.1/0.4.1) > /usr/local/bin/mill && chmod +x /usr/local/bin/mill'

      - run:
          name: install gpg2
          command: sh -c "apt update && apt install -y gnupg2 && mv /usr/bin/gpg /usr/bin/gpg-vanilla && echo '#!/bin/sh\n\n/usr/bin/gpg-vanilla --no-tty --pinentry loopback \$@' > /usr/bin/gpg && chmod 755 /usr/bin/gpg && cat /usr/bin/gpg"

      - run:
          name: install base64
          command: apt update && apt install -y cl-base64

      - run:
          name: test
          command: |
            mill all __.testLocal

      - run:
          name: check that the code is formatted properly
          command: ./scalafmt --test

      - run:
          name: publish to sonatype
          command: ./.circleci/publish.sh
