load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
    name = "utils",
    deps = [ "//src/io/iohk/multicrypto",
            "@decco//src/io/iohk/decco",
    ],
    external = [ "org.scalacheck:scalacheck%",
                 "com.typesafe.akka:akka-actor%"]
)

