load("//scala:rules.bzl", "scala_library", "scala_test")

scala_library(
    name = "utils",
    deps = [ "//src/io/iohk/crypto",
            "@codecs//src/io/iohk/codecs",
    ],
    external = [ "org.scalacheck:scalacheck%",
                 "com.typesafe.akka:akka-actor%"]
)

